### ISSUE TITLE
TypeError when task is manually marked success

### ISSUE THREAD

**Issue by yoichiwo7** [robinhood/airflow-prometheus-exporter#20]
When the non-executed task is manually marked success via Web UI or CLI, the following TypeError will be raised while collecting dag duration metrics.

```
  File "/usr/local/lib/python3.7/site-packages/airflow_prometheus_exporter/prometheus_exporter.py", line xxx, in collect
    dag_duration_value = (dag.end_date - dag.start_date).total_seconds()
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

## Detail

The dag duration uses TaskInstance's start_date to calculate the duration.

https://github.com/robinhood/airflow-prometheus-exporter/blob/43862bf0071e130b7b28e2b66a88942d67b16117/airflow_prometheus_exporter/prometheus_exporter.py#L90

The problem is when the **non-executed task** is manually marked success, the corresponding TaskInstance record's start_date has no value. This will set the dag's start_date to `None` value and cause the TypeError mentioned in this issue.

To fix the problem, we need to add filter to `dag_start_dt_query` so that TaskInstance record without start_date/end_date won't be included in the query result. The filter should look like the following code.

https://github.com/robinhood/airflow-prometheus-exporter/blob/43862bf0071e130b7b28e2b66a88942d67b16117/airflow_prometheus_exporter/prometheus_exporter.py#L273-L274

We already applied the fix in our private environment and now it works without error.

**Comment by DongshengXiong-old** [comment]
Any update for this issue?

**Comment by jefffarkas** [comment]
We're also experiencing the same issue.

**Comment by abhishekray07** [comment]
Sorry for the issues. I just pushed a fix and released a new version. Could y'all test and see if it fixes the problem?

**Comment by DongshengXiong-old** [comment]
@abhishekray07 we still have this issue since we have to mark some DAGs as success with skipped tasks. After manually adding start_state and end_state for skipped tasks, metrics can show up correctly. Maybe you need to add one more check like:
`TaskInstance.state != State.SKIPPED"`
